# this is for only server development with Docker Compose (not for version control, testing or profiling). The development happens inside the container.
version: "3.8"

services:
  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: chat-frontend

    working_dir: /app
    command: yarn dev -H 0.0.0.0 -p 3000
    volumes:
      - ./ui:/app
      - /app/node_modules # exclude node_modules from the volume to use the container's node_modules

    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8080

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-backend

    working_dir: /app
    entrypoint: /bin/bash -c
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload

    volumes:
      - ./src:/app/src
      - ./log:/app/log
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock

    ports:
      - 8080:8080
    env_file: .env

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  db:
    image: getmeili/meilisearch:v1.10
    container_name: chat-db
    ports:
      - 7700:7700
    volumes:
      - ./meilisearch-data:/app/data.ms
      - ./config.toml:/app/config.toml
    working_dir: /app
    command: meilisearch --config-file-path="./config.toml"
    restart: unless-stopped # Automatically restart unless manually stopped
